-- NETWORK INTRUSION DETECTION SYSTEM
-- Schema Creation Script

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE Network_Logs_Featured CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE Network_Logs CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

-- 1. Raw Network Logs (Simulating UNSW-NB15 dataset structure)
CREATE TABLE Network_Logs (
    log_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    src_ip        VARCHAR2(45),
    dst_ip        VARCHAR2(45),
    src_port      NUMBER,
    dst_port      NUMBER,
    protocol      VARCHAR2(10),
    service       VARCHAR2(20),
    state         VARCHAR2(20),
    duration      NUMBER,
    sbytes        NUMBER, -- Source bytes
    dbytes        NUMBER, -- Destination bytes
    sttl          NUMBER, -- Source to dest time to live
    dttl          NUMBER, -- Dest to source time to live
    attack_cat    VARCHAR2(50), -- e.g., 'Normal', 'DoS', 'Reconnaissance'
    label         NUMBER(1),    -- 0 for Normal, 1 for Attack
    log_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. Featured/Processed Logs (Ready for ML)
CREATE TABLE Network_Logs_Featured AS
SELECT * FROM Network_Logs WHERE 1=0; -- Empty structure copy

-- Indexes
CREATE INDEX idx_logs_ts ON Network_Logs(log_timestamp);
CREATE INDEX idx_logs_label ON Network_Logs(label);
CREATE INDEX idx_logs_attack ON Network_Logs(attack_cat);

COMMENT ON TABLE Network_Logs IS 'Raw network traffic logs for intrusion detection';

COMMIT;
