-- ORACLE HR PAYROLL & PERFORMANCE MANAGEMENT SYSTEM
-- Schema Creation

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE Leave CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE Performance CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE Attendance CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE Salary CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE Employee CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE Department CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE User_Login CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

-- 1. User Login (Authentication)
CREATE TABLE User_Login (
    user_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR2(50) UNIQUE NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    role          VARCHAR2(20) CHECK (role IN ('ADMIN', 'HR', 'MANAGER', 'EMPLOYEE')),
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. Department
CREATE TABLE Department (
    dept_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dept_name     VARCHAR2(100) NOT NULL,
    manager_id    NUMBER, 
    location      VARCHAR2(100)
);

-- 3. Employee
CREATE TABLE Employee (
    emp_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR2(100) NOT NULL,
    dept_id       NUMBER REFERENCES Department(dept_id),
    email         VARCHAR2(100) UNIQUE NOT NULL,
    phone         VARCHAR2(20),
    role          VARCHAR2(50),
    doj           DATE DEFAULT SYSDATE,
    status        VARCHAR2(20) DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'INACTIVE', 'ON_LEAVE')),
    user_id       NUMBER REFERENCES User_Login(user_id)
);

-- Add circular FK for Department Manager
ALTER TABLE Department ADD CONSTRAINT fk_dept_manager FOREIGN KEY (manager_id) REFERENCES Employee(emp_id);

-- 4. Salary (Base components)
CREATE TABLE Salary (
    emp_id        NUMBER PRIMARY KEY REFERENCES Employee(emp_id),
    basic         NUMBER(10, 2) NOT NULL,
    hra           NUMBER(10, 2) DEFAULT 0,
    allowance     NUMBER(10, 2) DEFAULT 0,
    tax_percent   NUMBER(5, 2) DEFAULT 10,
    last_updated  DATE DEFAULT SYSDATE
);

-- 5. Attendance
CREATE TABLE Attendance (
    att_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emp_id        NUMBER REFERENCES Employee(emp_id),
    work_date     DATE NOT NULL,
    hours_worked  NUMBER(4, 2) DEFAULT 8,
    overtime_hours NUMBER(4, 2) DEFAULT 0,
    CONSTRAINT uq_emp_date UNIQUE (emp_id, work_date)
);

-- 6. Performance
CREATE TABLE Performance (
    perf_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emp_id        NUMBER REFERENCES Employee(emp_id),
    review_month  VARCHAR2(7), -- Format: YYYY-MM
    rating        NUMBER(2, 1) CHECK (rating BETWEEN 1 AND 5),
    bonus_amount  NUMBER(10, 2) DEFAULT 0,
    reviewer_id   NUMBER REFERENCES Employee(emp_id),
    comments      VARCHAR2(500),
    review_date   DATE DEFAULT SYSDATE
);

-- 7. Leave
CREATE TABLE Leave (
    leave_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emp_id        NUMBER REFERENCES Employee(emp_id),
    leave_date    DATE NOT NULL,
    leave_type    VARCHAR2(20) CHECK (leave_type IN ('SICK', 'CASUAL', 'EARNED', 'UNPAID')),
    status        VARCHAR2(20) DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
    approved_by   NUMBER REFERENCES Employee(emp_id)
);

-- Indexes for Optimization
CREATE INDEX idx_emp_dept ON Employee(dept_id);
CREATE INDEX idx_emp_email ON Employee(email);
CREATE INDEX idx_att_date ON Attendance(work_date);
CREATE INDEX idx_perf_month ON Performance(review_month);

COMMENT ON TABLE Employee IS 'Core employee details';
COMMENT ON TABLE Performance IS 'Monthly performance reviews and ratings';

COMMIT;
